version: "3"
services:
  redis:
    image: redis
  mongo:
    image: mongo
    volumes:
      - "./data/mongo:/data/db"
  ui:
    image: ohmyform/ui
    environment:
      API_HOST: http://localhost:8090/graphql
      PORT: 5000
    ports:
      - "8080:5000"
  api:
    image: ohmyform/api
    environment:
      CREATE_ADMIN: "true"
      ADMIN_EMAIL: admin@local.host
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      MONGODB_URI: mongodb://mongo/ohmyform
      MAILER_URI: smtp://local.host
      REDIS_URL: redis://redis
      PORT: 5000
    links:
      - mongo
      - redis
    ports:
      - "8090:5000"
    depends_on:
      - mongo
      - redis
