# WARNING!! This is to build from source

# to use a version that is prebuilt copy one of the entries from the examples folder!


version: "3"
services:
  redis:
    image: redis
  mongo:
    image: mongo
    volumes:
      - "./data/mongo:/data/db"
  ohmyform:
    build: .
    environment:
      CREATE_ADMIN: "TRUE"
      MONGODB_URI: mongodb://mongo/ohmyform
      MAILER_URI: smtp://mail:1025
      PORT: 5000
    links:
      - mongo
      - redis
      - mail
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
  mail:
    image: mailhog/mailhog
    ports:
      - "5050:8025"
  mongoexpress:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "5051:8081"
    links:
      - mongo
    depends_on:
      - mongo
