version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - "./data/mongo:/data/db"
  ohmyform:
    image: ohmyform/ohmyform
    environment:
      CREATE_ADMIN: "TRUE"
      ADMIN_EMAIL: admin@local.host
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      MONGODB_URI: mongodb://mongo/ohmyform
      MAILER_URI: smtp://local.host
      PORT: 5000
    links:
      - mongo
    ports:
      - "8080:5000"
    depends_on:
      - mongo
