version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongo:/data/db"
  redis:
    image: redis
    ports:
      - "6379:6379"
#  api:
#    build: .
#    volumes:
#      - ".:/usr/src/app"
#    environment:
#      MONGODB_URI: mongodb://mongo/ohmyform
#      MAILER_URI: smtp://mail:1025
#      PORT: 3000
    #command: yarn start:dev
#    links:
#      - mongo
#      - mail
#    ports:
#      - "6100:3000"
#    depends_on:
#      - mongo
  mail:
    image: mailhog/mailhog
    ports:
      - "6001:8025"
      - "1025:1025"
  mongoexpress:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "6002:8081"
    links:
      - mongo
    depends_on:
      - mongo
